### ISSUE TITLE
Cloudflare check blocks access

### ISSUE THREAD

**Issue by vlna** [diezo/ProGPT#3]
Library no more works because cloudflare blocks access and website expect to prove user is a real human.

After KeyError exception at https://github.com/diezo/ProGPT/blob/2b96b6dbae1d6dfd604d1b844f341c9b889a5a80/ProGPT/Conversation.py#L128 file `progpt-response.txt` contains
`{"detail":{"message":"Client challenge required","code":"challenge_required"}}`

As I know Cloudflare uses cookies to identify valid session.

**Comment by diezo** [comment]
I'll have a look into this issue and update you on the same very soon.

**Comment by diezo** [comment]
@vlna the issue has been fixed and everything should now work fine.

**Comment by vlna** [comment]
@diezo: The issue still persists in v1.0.5

**Comment by diezo** [comment]
are you able to access chatgpt on web? try logging out and logging in again and this time use the fresh session id

**Comment by vlna** [comment]
@diezo: I logged out and logged in, took a new token but the issue still persists. I believe this is related to missing cloudflare cookies created as a captcha successful result.

**Comment by diezo** [comment]
i've tested it on my pc and it works fine. i've pushed a new update to progpt where u have to use the access token instead of cookies. check if that works for u.

u can also reach me on discord so we can have a better conversation on this. username: @gitdiezo

**Comment by vlna** [comment]
@diezo: I tested v1.0.6 and it does not work too. I think chatgpt webserver can provide different version of webpage based on some criteria hard to guess. I will try to reach you on discord.
