### ISSUE TITLE
ProGPT seems to not be working.

### ISSUE THREAD

**Issue by justin321123** [diezo/ProGPT#4]
`  File "/home/container/.local/lib/python3.12/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/bot.py", line 250, in chatgpt
    response = conversation.send(question)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/ProGPT/Conversation.py", line 128, in send
    if data["message"]["status"] != "finished_successfully":
       ~~~~^^^^^^^^^^^
KeyError: 'message'`

**Comment by diezo** [comment]
i'll fix this issue very soon and update you on the same. till then, please do give this repo a star to support progpt.
thanks

**Comment by justin321123** [comment]
Star has been given, thanks alot. I like the project alot and have been using it for a few days.

**Comment by diezo** [comment]
@justin321123 i've fixed the issue and everything should work fine now. thank you
